---
  - name: "Configure Basic Configuration on Arista Fabric"
    hosts: arista
    tasks:
      - name: "Configure Basic System config"
        eos_system:
          hostname: "{{ global.site|lower }}-{{ inventory_hostname}}"
          name_servers: "{{ global.dns }}"
          state: present
      - name: "Configure Users"
        eos_user:
          name: "{{ item.username }}"
          role: "{{ item.role }}"
          privilege: "{{ item.privilege | default(15) }}"
          configured_password: "{{ item.password }}"
          state: present
        loop: "{{ global.users }}"
      - name: "Configure the Physical Interfaces"
        eos_interface:
          name: "{{ item.port }}"
          enabled: true
          description: "{{global.site}} | Rpeer:{{item.peer}} | Rport: {{item.pport}}"
        with_items: "{{p2p_ip[inventory_hostname]}}"
      - name: "Configure IP Addresses"
        eos_l3_interface:
          name: "{{item.port}}"
          ipv4: "{{item.ip}}/{{global.p2p_prefix}}"
          state: present
        with_items: "{{p2p_ip[inventory_hostname]}}"
      #eos_l3_interfaces does not set `no switchport` for routed ports
      #https://github.com/ansible-collections/arista.eos/issues/101
      - name: "Disable Layer 2 feature for L3 Physcial Interfaces"
        eos_l2_interface:
          name: "{{ item.port}}"
          state: absent
        with_items: "{{p2p_ip[inventory_hostname]}}"