ospf_area: 0
ospf_metric: 10

svi_interfaces:
  - name: Vlan10
    ipv4: 10.1.10.0/24
    vrrp: yes
    ospf: passive
  - name: Vlan20
    ipv4: 10.1.20.0/24
    vrrp: yes
    ospf: passive
  - name: Vlan100
    ipv4: 10.1.100.0/24
    vrrp: yes
    ospf: passive
  - name: Vlan200
    ipv4: 10.1.200.0/24
    ospf: yes
    vrrp: no

core_l3_links:
  core01:
    - name: GigabitEthernet1/0
      description: wan01_G0/2
      ipv4: 10.3.1.0/30
      ospf: yes
      ospf_metric: 100
      peer: wan01
    - name: Loopback0
      ipv4: "{{ loopback_prefix | ipv4(hst_router_id) | ipaddr('address') + '/32'}}"
      ospf: passive
  core02:
    - name: GigabitEthernet1/0
      description: wan02_G0/2
      ipv4: 10.3.1.4/30
      ospf: yes
      ospf_metric: 200
      peer: wan02
    - name: Loopback0
      ipv4: "{{ loopback_prefix | ipv4(hst_router_id) | ipaddr('address') + '/32'}}"
      ospf: passive