isp_l3_links:
    - name: GigabitEthernet0/1
      description: "wan01_G0/4"
      peer: wan01
      ipv4: 192.168.1.2/30

    - name: GigabitEthernet0/2
      description: "wan02_G0/4"
      peer: wan02
      ipv4: 192.168.1.6/30

bgp_peers:
    - peer: 192.168.1.1
      description: "eBGP sesstion to ips01"
      redistribute: ospf
      route_map: cust_export
    - peer: 192.168.1.5
      description: "eBGP sesstion to ips01"
      redistribute: ospf
      route_map: cust_export


route_policy:
  cust_export:
    - id: 10
      match: ospf
      set:
        as_path: "{{bgp_as}}"
  wan02: