interfaces:
  core01:
  - name: GigabitEthernet0/1
    description: access01_G0/1
    mode: trunk
  - name: GigabitEthernet0/2
    description: access02_G0/1
    mode: trunk
  - name: GigabitEthernet0/3
    description: core02_g0/3
    mode: trunk
  core02:
  - name: GigabitEthernet0/1
    description: access01_G0/2
    mode: trunk
  - name: GigabitEthernet0/2
    description: access02_G0/2
    mode: trunk
  - name: GigabitEthernet0/3
    description: core01_g0/3
    mode: trunk
  access01:
  - name: GigabitEthernet0/1
    description: core01_G0/1
    mode: trunk
  - name: GigabitEthernet0/2
    description: core02_g0/1
    mode: trunk
  - name: GigabitEthernet0/3
    description: Data_vlan
    mode: access
    vlan: 10
  access02:
  - name: GigabitEthernet0/1
    description: core01_G0/2
    mode: trunk
  - name: GigabitEthernet0/2
    description: core02_g0/2
    mode: trunk
  - name: GigabitEthernet0/3
    description: Voice_vlan
    mode: access
    vlan: 20
  - name: GigabitEthernet1/0
    description: Web_vlan
    mode: access
    vlan: 100

vlans:
  - name: Data
    vlan_id: 10
  - name: Voice
    vlan_id: 20
  - name: Web
    vlan_id: 100