ansible_network_os: ios
ansible_connection: network_cli
ansible_user: admin
ansible_password: cisco
ansible_become: yes
ansible_become_password: cisco
ansible_become_method: enable

domain_name: cisco.com
name_servers:
 - 172.20.1.250
 - 172.20.1.251
ntp_server: 172.20.1.17

intf_mtu: 1500
intf_duplex: full